create table IF NOT EXISTS address (id bigint generated by default as identity, city varchar(255), country varchar(255), house_name varchar(255), street_name varchar(255), zip_code integer, employee_id bigint, primary key (id));
create table IF NOT EXISTS employee (id bigint generated by default as identity, enabled boolean, first_name varchar(255) not null, last_name varchar(255), salary double, primary key (id));

create sequence IF NOT EXISTS hibernate_sequence start with 1 increment by 1;
create table IF NOT EXISTS address_aud (id bigint not null, rev integer not null, revtype tinyint, city varchar(255), country varchar(255), house_name varchar(255), street_name varchar(255), zip_code integer, employee_id bigint, primary key (id, rev));
create table IF NOT EXISTS employee_aud (id bigint not null, rev integer not null, revtype tinyint, enabled boolean, first_name varchar(255), last_name varchar(255), salary double, primary key (id, rev));
create table IF NOT EXISTS app_revision (id bigint not null, timestamp bigint not null, user_name varchar(255), comment varchar(255), primary key (id));
alter table address_aud add constraint if not exists address_aud_FK foreign key (rev) references app_revision;
alter table employee_aud add constraint if not exists employee_aud_FK foreign key (rev) references app_revision;